
server:
  servlet:
    context-path: /
  port: 9002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: store-app
logging:
  level:
    org.github.hoorf: trace


