
server:
  servlet:
    context-path: /
  port: 9001
eureka:
  client:
    service-url:
      defaultZone: http://eureka-host:8761/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: account-app
logging:
  level:
    org.github.hoorf: trace


